### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by marcelosousa**

### CODE REVIEW

**Comment by marcelosousa** [comment]
/reviewpad robin "Provide a summary of this pull request"

**Comment by marcelosousa** [comment]
/reviewpad robin "Provide a summary of this pull request"

**Comment by marcelosousa** [comment]
/reviewpad robin ""Provide a summary of this pull request""

**Comment by marcelosousa** [comment]
/reviewpad robin "Provide a summary of this pull request"

**Comment by marcelosousa** [comment]
/reviewpad robin "Provide a summary of this pull request"

**Comment by ferreiratiago** [comment]
/reviewpad robin "Please describe the changes file by file"

**Comment by ferreiratiago** [comment]
/reviewpad robin "Is there any potential issues with these changes?"

**Comment by ferreiratiago** [comment]
/reviewpad robin "What should I know before reviewing this code?"

**Comment by marcelosousa** [comment]
/reviewpad robin What should I know before reviewing this code?

**Comment by ferreiratiago** [comment]
/reviewpad robin "Is there any semantic changes? Simple say Yes or No."

**Comment by marcelosousa** [comment]
/reviewpad robin generate a summary for this pull request.

**Comment by ferreiratiago** [comment]
/reviewpad robin Is there any semantic changes? Answer only the values "Yes" or "No"

**Comment by ferreiratiago** [comment]
/reviewpad robin Is there any semantic changes? Simply say "Yes" or "No". Add no more text to the answer.

**Comment by ferreiratiago** [comment]
/reviewpad robin Is there any semantic changes? Simply say "Yes" or "No". Add no more text to the answer. Add no punctuation.

**Comment by ferreiratiago** [comment]
/reviewpad robin Is there any semantic changes? Simply say "Yes" or "No". Add no more text and punctuation to the answer.

**Pull request closed without merging**
